In [1]:
import numpy as np

In [2]:
A = np.random.randn(4,3)
B = np.random.randn(3,4)
R = np.zeros((4,4))

In [3]:
for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        result = 0
        for k in range(A.shape[1]):
            result += A[i,k] * B[k,j]
        R[i,j] = result

In [4]:
R

array([[ 2.53138815, -1.53531781,  0.21051397, -0.65806494],
       [-1.25575587,  0.17818193,  0.46724524,  0.16669553],
       [-1.35231785,  0.90970133,  0.06817999,  0.6156376 ],
       [-1.01161745,  0.1127492 ,  0.72268577,  0.40808725]])

In [5]:
np.matmul(A,B)

array([[ 2.53138815, -1.53531781,  0.21051397, -0.65806494],
       [-1.25575587,  0.17818193,  0.46724524,  0.16669553],
       [-1.35231785,  0.90970133,  0.06817999,  0.6156376 ],
       [-1.01161745,  0.1127492 ,  0.72268577,  0.40808725]])

In [42]:
W , H = 10 , 10
image = np.random.randn(W,H)
kernel_size = 3
P = 0
S = 1
kernel = np.random.randn(kernel_size,kernel_size)
output_size = ((W - kernel_size + 2 * P) / S + 1 , (H - kernel_size + 2 * P)/S + 1)

In [9]:
resize_kernel_size = (64,100)

In [32]:
resize_kernel = np.zeros(resize_kernel_size)

In [33]:
resize_kernel

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [34]:
stride_offset = 0
for row in range(resize_kernel_size[0]):
    offset = stride_offset
    for i in range(kernel_size):
        resize_kernel[row,offset:offset+kernel_size] = kernel[i,:]
        offset +=W
    stride_offset +=1

In [35]:
resize_kernel

array([[-1.26784583,  0.44567945, -2.19752328, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        , -1.26784583,  0.44567945, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -1.26784583, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [50]:
resize_kernel[1,0]

0.0

In [25]:
kernel

array([[-1.26784583,  0.44567945, -2.19752328],
       [ 0.24630602, -0.16908024, -0.18457367],
       [ 0.24259648, -2.07597546, -0.91838993]])

In [49]:
np.matmul(resize_kernel,image.reshape(-1,1))

array([[-0.39924182],
       [ 0.97115046],
       [-2.53832429],
       [-3.81373261],
       [-1.66870807],
       [ 2.75442334],
       [ 3.70656234],
       [ 1.1613438 ],
       [-0.56642535],
       [-1.36355955],
       [-0.47094055],
       [ 1.8977934 ],
       [-2.45078925],
       [ 0.39568413],
       [-4.97246336],
       [ 3.64770024],
       [ 7.91278989],
       [ 3.81061066],
       [-0.93157904],
       [-1.87568086],
       [-0.93566045],
       [-0.44436848],
       [ 0.81799367],
       [ 3.12199241],
       [ 0.85658014],
       [ 2.43445073],
       [-1.29670296],
       [-2.69443119],
       [-5.47038213],
       [ 0.83894547],
       [-1.45945199],
       [-1.00998444],
       [ 3.73579108],
       [-5.876801  ],
       [ 2.63470656],
       [-1.1462492 ],
       [ 0.90586401],
       [-0.02268684],
       [-0.26887215],
       [ 0.77190918],
       [-0.05623203],
       [ 4.73508272],
       [ 3.71697637],
       [ 4.81674494],
       [ 1.24047551],
       [ 0

In [47]:
image.reshape(-1,1).shape

(100, 1)

In [48]:
resize_kernel.shape

(64, 100)

In [52]:
image.shape

(10, 10)

In [57]:
 from sympy import *
import sympy

In [56]:
l ,a,y,z ,w ,x = symbols("l a y z w x")

In [59]:
z = w *x
a = (sympy.exp(z) / (1 + sympy.exp(z)))
l = 0.5 * (a - y) ** 2

In [60]:
print(sympy.latex(sympify(diff(l,w))))

0.5 \left(- y + \frac{e^{w x}}{e^{w x} + 1}\right) \left(\frac{2 x e^{w x}}{e^{w x} + 1} - \frac{2 x e^{2 w x}}{\left(e^{w x} + 1\right)^{2}}\right)
